### ISSUE TITLE
iob.js returning 0, should revert back to lasttimestamp which calculates the iob correctly including the bolus

### ISSUE THREAD

**Issue by amazaheri** [openaps/openaps-js#1]

**Comment by scottleibrand** [comment]
Not quite following: can you include more repro details or a PR with your suggested fix?

-Scott

**Comment by amazaheri** [comment]
Added a bolus and job.js calculated the job as 0. Reverting back from now to lastTimestamp calculated the job as expected. As 0.989. From

**Comment by scottleibrand** [comment]
How long is that true for? Wondering if it's due to the pump time being in the future? Can you fit push to your openaps-dev repo all the files in the state necessary to repro it, so we can take a look (probably tomorrow)?

-Scott

On Wed, Jul 1, 2015 at 11:15 PM -0700, "Ali" notifications@github.com wrote:

Added a bolus and job.js calculated the job as 0. Reverting back from now to lastTimestamp calculated the job as expected. As 0.989. From

**Comment by amazaheri** [comment]
hmmm, it could be a false alarm. I tried again and its working, pump time is set correctly. I have my eye on it.
