### ISSUE TITLE
+/- determine-basal.js

### ISSUE THREAD

**Issue by infoneo** [openaps/openaps-js#13]
In the hight temp rate calculation there is: "var rate = profile_data.current_basal - (2 \* insulinReq);" shouldn't be "var rate = profile_data.current_basal + (2 \* insulinReq);"?

**Comment by scottleibrand** [comment]
It's a double negative with the way insulinreq is calculated right above. The logic is correct, but we could reverse it in both places if that'd make it easier to read. 

I also need to fix the way I'm using max(0) and snoozebg: right now it's temping all the way to zero any time the bolus snooze range goes below the target range, instead of being more gradual like I intended.

**Comment by infoneo** [comment]
No it's no need to change :) Once, I have noticed, that there was "low bolus" calculated (below base bolus) instead of high. I haven't saved logs unfortunately. I'm closing issue.
