### ISSUE TITLE
Average delta calculation - need to exclude calibration records

### ISSUE THREAD

**Issue by infoneo** [openaps/openaps-js#15]
There is a need to exclude calibration records (bg < 10) from average delta calculation in getLastGlucose().

After the calibration period I've found out following situation (in my script I have removed protections like maxsafebasal to see real values):

IOB: 3.30, Bolus IOB: 2.21
Avg. Delta: 64.0, BGI: -10.6
15m deviation: 224
BG: 197-1 -> 315-386 (Unadjusted: 91-162)
etermine-basal://text/shell/requestedtemp.json.new
reporting requestedtemp.json.new
{"carbs_hr":28,"max_iob":3,"dia":3,"type":"current","current_basal":1,"max_daily_basal":1.2,"max_basal":9, "max_bg":120,"min_bg":100,"carbratio":10,"sens":32}
{"iob":3.2998203002000004,"activity":0.06633862433862434,"bolusiob":2.21103056005}
{"temp":"absolute","duration":30,"rate":13.8}

The rate was calculated to 13.8 in spite of flat trend - glucose levels were about 200mg.

**Comment by infoneo** [comment]
sorry, a haven't noticed, that this was already patched :)

**Comment by amazaheri** [comment]
Yeah, I did that patch a while back. I have already asked @bewest  to see if we can get raw data to use although I rather be offline during calibration or ??? To avoid the following.

![wp_ss_20150803_0001](https://cloud.githubusercontent.com/assets/8312775/9091025/b076f74e-3b52-11e5-87d4-09f51fdf22cb.png)

@scottleibrand  has some good suggestions on dealing with sudden spikes or lows due to faulty readings not covered by <10  https://github.com/openaps/openaps-js/issues/14
