### ISSUE TITLE
[dev] maxSafeBasal variable is leaking to global space

### ISSUE THREAD

**Issue by gordonbrander** [openaps/openaps-js#45]
In `oref0-determine-basal.js` (dev branch) `maxSafeBasal` is initialized in 2 places without the `var` keyword.

https://github.com/openaps/openaps-js/blob/dev/bin/oref0-determine-basal.js#L308
https://github.com/openaps/openaps-js/blob/dev/bin/oref0-determine-basal.js#L281

Omitting `var` makes this a shared a global variable. I don't _think_ this was the intention, so I thought I would call it out, since it could cause surprising behavior if relied on to be local.

**Comment by gordonbrander** [comment]
Oops nvm, I followed the link from [this mailing list thread on unit tests](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!searchin/openaps-dev/unit$20test/openaps-dev/GN53JySINcg/ZuNEOzLWCAAJ), but didn't realize this repo was deprecated.

**Comment by scottleibrand** [comment]
Thx for poking at this kind of stuff. Do you see anywhere in the oref0 repo where I make the same mistake (or the inverse, of using var for things I really shouldn't)? If so, could you open issues (or PRs to fix) over there, if you haven't already?

**Comment by gordonbrander** [comment]
Thanks! I did take a peek at oref0 and didn't see anything obvious. Will definitely submit PRs if I do find anything I can fix.

**Comment by scottleibrand** [comment]
Cool. I did find one similar thing, where the profile object was being set at the top of the unit tests, but then wasn't being reset after the meal assist code changed it. That was a rather weird bug to troubleshoot, but it turned out the easiest fix was switching to a local var in the determine-basal code. I'm still not sure I understand scoping on js properly, though, so I'm sure there are more places I did it wrong.
